### ISSUE TITLE
Migrate to react

### ISSUE THREAD

**Issue by maizy** [maizy/wlb#6]
impl - https://github.com/maizy/wlb/pull/9

**Comment by httpsprayag** [comment]
hey @maizy, please provide exact issue and description, i would like to contribute in react project.

**Comment by maizy** [comment]
> hey @maizy, please provide exact issue and description, i would like to contribute in react project.

The idea is simple - rewrite [main.js](https://github.com/maizy/wlb/blob/7e704d241726a3b02def9c5f47b313466b831f38/docs/js/main.js) using react components and state management.

But this is a tiny pet project, and I don't think it's worth doing. I'm going to do it to revise react, which I last wrote many years ago.
